export type Tecnico = {
  tecnicoid: string;
  tecnicouniqueid: string;
  tecnicolocked?: string;
  tecnicoservername?: string;
  tecnico_vpa_id: string;
  tecnico_name?: string;
  tecnico_register?: string;
  tecnico_password: string;
  tecnico_mac?: string;
  tecnico_status?: string;
  tecnico_key?: string;
  tecnicoapikeymobile?: string;
  tecnicoapikeysoftware?: string;
  tecnicokeyprivate?: string;
  tecnicolevelaccess?: string;
  tecnicotoken?: string;
  tecnicodevicestatus?: string;
  tecnicoapikeyhardware?: string;
  dbversion?: string;
  tecnicoemail?: string;
  tecnicophone?: string;
  user_system_type?: string;
  title: string;
  description: string;
  published: string;
};
