//#  www.airspacedefense.org
//#  Eng Marcelo Anjos
//#  marcelu.phd@gmail.com
//#  10/04/2020

import { Dimensions, StyleSheet } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;
const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  bgImage: {
    flex: 1,
    top: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    width: SCREEN_WIDTH * 0.95,
    flexDirection: 'row',
    borderRadius: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  headerBackIcon: {
    marginRight: 15,
  },
  datoAnimal: {
    textAlign: 'center',
  },

  textInfo: {
    fontSize: 15,
    marginTop: 10,
    alignItems: 'center',
    color: 'rgba(52, 52, 52, 0.6)',
  },
  headerText: {
    fontSize: 20,
    marginRight: 10,
    color: '#ffffff',
  },
  title: {
    textAlign: 'center',
    fontSize: 30,
    marginBottom: 10,
    marginTop: 10,
    color: 'white',
    fontWeight: 'bold',
  },
  title2: {
    textAlign: 'center',
    fontSize: 15,
    marginTop: 10,
    color: 'black',
    fontWeight: 'bold',
  },
  image: {
    marginLeft: 20,
  },
  termsCheckBox: {
    marginTop: 24,
  },
  mainBody: {
    flex: 1,
    justifyContent: 'center',
  },
  SectionFrame: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'transparent',
    marginTop: -10,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
  },

  SectionFrame2: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'transparent',
    marginTop: -5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
  },
  SectionFrame3: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'transparent',
    alignSelf: 'center',
  },
  SectionFrame4: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'transparent',
    marginTop: -5,
    alignSelf: 'center',
  },
  IconTipoDe: {
    marginTop: 7,
    marginLeft: 120,
  },
  IconPlus: {
    marginTop: 38,
    marginLeft: -25,
  },
  IconPlus2: {
    marginTop: 12,
    marginLeft: -25,
  },
  IconPlus3: {
    marginTop: 12,
    marginLeft: -25,
  },
  IconPlus4: {
    marginTop: 12,
    marginLeft: -25,
  },
  IconSigla: {
    marginTop: 7,
    marginLeft: 85,
  },
  IconColor: {
    marginTop: 7,
    marginLeft: 130,
  },
  IconNumero: {
    marginTop: 7,
    marginLeft: 65,
  },
  IconTipoDe2: {
    marginTop: 7,
    marginLeft: 150,
  },
  SectionStyle: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    height: 40,
    marginTop: 35,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#474887',
  },
  SectionStyle2: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    alignSelf: 'center',
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#474887',
  },
  SectionStyle3: {
    backgroundColor: 'white',
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: 'white',
  },
  SectionCedula: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#474887',
  },

  SectionCorreo: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#474887',
  },

  SectionTelefono: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    height: 40,
    marginTop: 5,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#474887',
    marginBottom: 30,
  },

  SectionContraseña: {
    backgroundColor: 'white',
    flexDirection: 'row',
    height: 40,
    marginTop: 15,
    marginLeft: 35,
    marginRight: 35,
    margin: 15,
    borderWidth: 2,
    borderRadius: 30,
    borderColor: 'white',
  },
  inputStyle: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: 10,
    marginTop: -10,
    fontSize: 15,
  },
  inputStyle2: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: -80,
    marginTop: -10,
    fontSize: 15,
  },
  inputStylePeso: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: 35,
  },
  inputStylePesoSalida: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: 30,
  },
  inputStyleNGuia: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: -60,
  },
  inputStyleAngus1: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: 65,
  },
  inputStyleCantidad: {
    flex: 1,
    color: 'rgba(52, 52, 52, 0.6)',
    marginRight: 90,
  },
  registerTextStyle: {
    color: 'rgba(52, 52, 52, 0.6)',
    textAlign: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
    fontSize: 18,
    width: 120,
    height: 35,
    borderWidth: 1,
    borderRadius: 8,
    marginLeft: 15,
    marginRight: 15,
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
  },
  forgotStyle: {
    height: 100,
    flexDirection: 'row',
    borderRadius: 6,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
    marginTop: 5,
  },
  MessageContainer: {
    marginTop: 5,
    marginRight: 10,
    marginLeft: 10,
  },
  titleMsg: {
    fontSize: 20,
    marginBottom: 2,
    marginTop: 5,
    color: 'white',
    fontWeight: 'bold',
  },
  MessageBtn: {
    marginRight: 10,
  },
  SectionStyleText: {
    marginLeft: 20,
  },
  SectionStyleText2: {
    marginLeft: 10,
  },
  SectionStyleText4: {
    marginLeft: 12,
  },
  returnButton: {
    backgroundColor: '#007F5F',
    width: width - 230,
    alignItems: 'center',
    padding: 5,
    borderRadius: 10,
    marginBottom: 30,
    marginTop: 5,
    marginLeft: 40,
  },
  returnButtonText: {
    color: '#e02041',
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 10,
  },
  messages: {
    flexDirection: 'row',
    borderRadius: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#33c37d',
    marginBottom: 20,
  },
  buttonStyle: {
    backgroundColor: '#7DE24E',
    borderWidth: 0,
    color: '#FFFFFF',
    borderColor: '#6cc9e0',
    height: 50,
    alignItems: 'center',
    borderRadius: 30,
    marginLeft: 110,
    marginRight: 110,
    marginBottom: 10,
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  messageReturnButton: {},
});
