/* eslint-disable max-lines-per-function */
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./'],
          alias: {
            '@': './src',
            '@env': './src/core/env.js',
            '@config': './config',

            '@api': './src/api',
            '@app': './src/app',
            '@assets': './src/assets',
            '@colors': './src/shared/theme/colors',
            '@common': './src/common',
            '@components': './src/components',
            '@context': './src/context',
            '@core': './src/core',
            '@data': './src/data',
            '@database': './src/database',
            '@dtos': './src/dtos',
            '@font-size': './src/shared/theme/font-size',
            '@fonts': './src/shared/theme/fonts',
            '@hooks': './src/hooks',
            '@i18n': './src/i18n',
            '@layouts': './src/layouts',
            '@libs': './src/libs',
            '@local-storage': './src/services/local-storage',
            '@model': './src/model',
            '@modules': './src/modules',
            '@navigation': './src/navigation',
            '@navigator': './src/navigator',
            '@pages': './src/pages',
            '@redux': './src/redux',
            '@routes': './src/routes',
            '@scenes': './src/scenes',
            '@services': './src/services',
            '@shared-components': './src/shared/components',
            '@shared-constants': './src/shared/constants',
            '@screens': './src/screens',
            '@styles': './src/styles',
            '@stores': './src/stores',
            '@themes': './src/themes',
            '@translations': './src/translations',
            '@type': './src/type',
            '@theme': './src/theme',
            '@ui': './src/ui',
            '@utils': './src/utils',
          },
          extensions: [
            '.ios.ts',
            '.android.ts',
            '.ts',
            '.ios.tsx',
            '.android.tsx',
            '.tsx',
            '.jsx',
            '.js',
            '.json',
          ],
        },
      ],
      ['nativewind/babel', { mode: 'compileOnly' }],
      'react-native-reanimated/plugin',
    ],
  };
};
