/* eslint-disable unicorn/filename-case */
// ########################################
export interface CustomerDTO {
  customerId: string;
  customerEmail: string;
  customerPhone: string;
  customerUniqueId: string;
  customerLocked: string;
  customerServerName: string;
  customer_vpa_id: string;
  customer_name: string;
  customer_register: string;
  customer_password: string;
  customer_mac: string;
  customer_status: string;
  customer_key: string;
  customerApiKeyMobile: string;
  customerApiKeySoftware: string;
  customerKeyPrivate: string;
  customerLevelAccess: string;
  customerToken: string;
  customerDeviceStatus: string;
  customerApiKeyHardware: string;
  customerPermission: string;
  customerAddress: string;
  avatar_id: string;
  avatar_face: string;
  wallet_id: string;
  first_name: string;
  last_name: string;
  address: string;
  stateAbbr: string;
  city: string;
  zipcode: string;
  avatar: string;
  birthday: string;
  first_seen: string;
  last_seen: string;
  has_ordered: boolean;
  latest_purchase: string;
  has_newsletter: boolean;
  groups: string;
  nb_commands: any;
  total_spent: any;
  created_at?: any;
  updated_at?: any;
}
