export const coibfe = {
  // coibfeInput_coibfe_id: '1', // database id to update // TODO: change to auto id
  coibfeId: '49990001',
  coibfeKey: '',
  coibfeToken: '',
  coibfeCodigoV: 'abcf1',
  coibfeDestino: 'Union Europea', // destino,
  coibfeFinalidad: 'Faena',
  coibfeTransporte: 'Terrestre',
  coibfeAniNovillos: '1',
  coibfeAniToros: '2',
  coibfeAniVacas: '3',
  coibfeAniVaquillas: '4',
  coibfeAniOtros: '5',
  coibfeAniTotal: '15', //animales_total,
  coibfeAniHilton: '3',
  coibfeTecnico_VPA_ID: '999',
  coibfeTecnicoName: 'Marcelo Anjos',
  coibfeFrigorificoName: 'Frigorifico Belem',
  coibfeFrigorifico_ID: '1000002',
  coibfeProductorName: 'Los Lazos',
  coibfeProductor_ID: '1500000',
  coibfeProductorSitrap: 'AAAA',
  coibfePropriedadName: 'Hacienda Los Lazos',
  coibfePropriedad_ID: '111111111',
  coibfePropriedadSigor: '100001110000',
  coibfePropriedadSitrap: 'BBBB',
  coibfePropriedadDepartamento: 'Central',
  coibfePropriedadDistrito: 'Asuncion',
  coibfePropriedad_productor_id: 'coibfePropriedad_productor_id',
  coibfePrecinto1: '1234567',
  coibfePrecinto2: '8912345',
  coibfePrecinto3: '6789012',
  coibfePos_ID: 'aaaa1111',
  coibfePosLatitud: '-30.1234',
  coibfePosLongitud: '55.1234',
  coibfePosDateTime: '22/01/2022 12:45',
  coibfePosApiKeyMobile: 'coibfePosApiKeyMobile',
  coibfeOBS: '',
  coibfeDocNroProp: '8089161',
  coibfeDocDigProp: '6',
  coibfeDocOrigAbrev: 'PY',
  coibfeDocTipoAbrev: 'RUC',
  coibfeErroCode: '',
  coibfeErroMessage: '',
  coibfeAnimales: '',
  coibfe_isSinc: '',
  coibfe_print: '0',
};
// -------------------------------------------------------------
